# Generated by Django 3.2.9 on 2021-11-26 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
