# Generated by Django 3.2.9 on 2021-12-02 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circles', '0003_rename_is_verified_circle_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membreship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the model was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('is_admin', models.BooleanField(default=False, help_text="Circle admins can update the circle's data and manage its members", verbose_name='circle admin')),
                ('used_invitations', models.PositiveIntegerField(default=0)),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('rides_offerd', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Only activate users are allowed to interact in the circle', verbose_name='activate status')),
                ('circles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circles.circle')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('remaninig_invitation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='circle',
            name='members',
            field=models.ManyToManyField(through='circles.Membreship', to=settings.AUTH_USER_MODEL),
        ),
    ]
